<a href="https://colab.research.google.com/github/navi004/cse3041/blob/main/NumpyEx_1_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [29]:
#Creating a rank 1 array
arr = np.array([1,2,3])
print("Array with rank : 1 \n",arr)
#Printing the datatype
print(type(arr))
#Creating a rank 2 Array
arr = np.array([[1,2,3],[4,5,6]])
#printing the dimensions
print(arr.ndim)
#printing shpae of the array
print(arr.shape)
print("Array with Rank 2 : \n",arr)
#Printing type of elements
print(arr.dtype)

Array with rank : 1 
 [1 2 3]
<class 'numpy.ndarray'>
2
(2, 3)
Array with Rank 2 : 
 [[1 2 3]
 [4 5 6]]
int64


In [30]:
#Creating a list of array with float data type
a = np.array([[1,2,3],[4,5,6]],dtype = float)
print("Array printed using passed list : \n",a)

Array printed using passed list : 
 [[1. 2. 3.]
 [4. 5. 6.]]


In [31]:
#Creating array from tuple
b = np.array(((1,2,3),(4,5,6)))
print("Array is printed using passed tuple : \n",b)


Array is printed using passed tuple : 
 [[1 2 3]
 [4 5 6]]


In [34]:
#arange
#arange(start,stop,step, [dtype=None])
f = np.arange(0, 30,5)
print("A sequential arrayw with steps of 5:\n",f.reshape(2,3))

A sequential arrayw with steps of 5:
 [[ 0  5 10]
 [15 20 25]]


In [36]:
#linspace
 #(start,stop,num = 50,endpoint=True,restep = False)
g = np.linspace(0, 5,10)
print("A sequential array with 10 values between 0 and 5 : \n",g,"\n")
print("Two dimensional array of above elements : \n",g.reshape(2,5))

A sequential array with 10 values between 0 and 5 : 
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ] 

Two dimensional array of above elements : 
 [[0.         0.55555556 1.11111111 1.66666667 2.22222222]
 [2.77777778 3.33333333 3.88888889 4.44444444 5.        ]]


In [7]:
#Reshaping the array
arr = np.array([[1,2,3,4],
                  [5,2,4,2],
                    [1,2,0,1]])

newarr = arr.reshape(2,2,3)
print("Original array : \n",arr)
print("Reshaped array : \n",newarr)

Original array : 
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array : 
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


In [42]:
#Indexing
#Arr[i,j,k]
#One dimensional
arr1 = np.array([12,2,34])
print("second element is :\n",arr1[1])

#Two dimensional
arr2 = np.array([[1,2,4],[4,69,5]])
print(arr2)
print("First row second element is :\n",arr2[0,1])

# 3 - d Array
arr3 = np.array([[[1,34,6,3],[3,6,8,90]],[[2,5,78,34],[34,67,34,67]]])
print(arr3)
print(arr3[0,1,2])

second element is :
 2
[[ 1  2  4]
 [ 4 69  5]]
First row second element is :
 2
[[[ 1 34  6  3]
  [ 3  6  8 90]]

 [[ 2  5 78 34]
  [34 67 34 67]]]
8


In [55]:
#Slicing
#A[start:stop:steps]
#1 -d Array
arr1 = np.array([1,2,5,7,3,47])
print("Printing 1 to 4 elements :\n",arr1[1:5])
print("Printing Even Index Elements",arr1[::2])
slicedarr = arr[:2, ::2]
print ("\nArray with first 2 rows and alternate columns(0 and 2):\n", slicedarr)

#2-d array
arr2 = np.array([[23,45,67],[32,45,24],[21,67,34]])
print("printing the 0 and 1 elements in 1st row \n",arr2[1,0:2])

Printing 1 to 4 elements :
 [2 5 7 3]
Printing Even Index Elements [1 5 3]

Array with first 2 rows and alternate columns(0 and 2):
 [[1 3]
 [4 6]]
printing the 0 and 1 elements in 1st row 
 [32 45]


In [13]:
#data types
#arr.dtype
#astype() - to convert the datatype
"""i - integer
f - flaot
c - complex
S - string """
#arr.copy() - does not change the original array
#arr.view() - changes the original array


'i - integer\nf - flaot\nc - complex\nS - string '

In [56]:
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42
print("Original array : \n",arr)
print("View \n", x)

#2-d Array
arr1 = np.array([[23,45,23,45],[12,89,67,89]])
y = arr1.view()
arr1[0,1] = 42
print("Original array : \n",arr1)
print("View \n", y)

Original array : 
 [42  2  3  4  5]
View 
 [42  2  3  4  5]
Original array : 
 [[23 42 23 45]
 [12 89 67 89]]
View 
 [[23 42 23 45]
 [12 89 67 89]]


In [62]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0]  =42
print(arr)
print(x)

#2-d Array
arr1 = np.array([[23,45,23,45],[12,89,67,89]])
y  = arr1.copy()
arr1[0,1]  = 42
print("\n2d - array\n",arr1)
print(y)

[42  2  3  4  5]
[1 2 3 4 5]

2d - array
 [[23 42 23 45]
 [12 89 67 89]]
[[23 45 23 45]
 [12 89 67 89]]


In [67]:
#iterating

 #2d array
arr1 = np.array([[4,5,6], [1,3,4]])
print("2d array\n")
for y in arr:
 print(y)

#Concatenation
#arr = np.concatenate((arr1,arr2))
#for two dimensional
#arr = np.concatenate((arr1,arr2,axis = 1)) - concatenation with rows
#arr = np.concatenate((arr1,arr2,axis = 0)) - concatenation with columns

2d array

5
6
7


In [16]:
#splitting
#np.arr_split()
#searching
arr = np.array([1,2,4,6,3,5,4])
x = np.where(arr == 4)
print(x)

y = np.where(arr%2 == 0)
print(y)


(array([2, 6]),)
(array([1, 2, 3, 6]),)


In [17]:
#searching sorted array
arr = np.array([5,6,8,9])
x = np.searchsorted(arr,7)
print(x)

2


In [18]:
#Basic Unary Operations
a = np.array([1,2,5,3])
print("Original Array :\n")
#Increment
print("Adding 1 to every element :",a+1 )
#Decrement
print("Subtracting 1 from every element :",a-1)


Original Array :

Adding 1 to every element : [2 3 6 4]
Subtracting 1 from every element : [0 1 4 2]


In [25]:
a = np.array([[1,2],[3,4]])
b = np.array([[4,3],[2,1]])
print("Original Array:\n \nA\n",a,"\nB\n",b)
#add arrays
print("Array sum : \n",a+b)
#multiply arrays
print("Arrays multiplication : \n",a*b)
#difference
print("Arrays difference : \n",a-b)
#matrix multiplication
print("Matrix Multiplication : \n",a.dot(b))

Original Array:
 
A
 [[1 2]
 [3 4]] 
B
 [[4 3]
 [2 1]]
Array sum : 
 [[5 5]
 [5 5]]
Arrays multiplication : 
 [[4 6]
 [6 4]]
Arrays difference : 
 [[-3 -1]
 [ 1  3]]
Matrix Multiplication : 
 [[ 8  5]
 [20 13]]


In [ ]:
#Universal Functions
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([3,7,9,8,2,33])
newarr =

In [ ]:
#np.trunc
#np.around
#np.floor
#np.ceil
#np.gcd
#np.gcd.reduce
#np.log2(arr)
#np.log10(arr)
#np.log(arr)