1. To reduce air pollution, private vehicles will be allowed to run on the streets on
   alternate days depending on their Vehicle Registration Number (eg. TN75AA7116).

- Given a vehicle number, write a function in python to extract the last four digits and
  apply the conditions in the given order to find the day order.
  *  If the sum of the digits is even and if the number is prime, the vehicle will run
  on Mon, Wed, Fri and Sunday
  *  Or if the product of digits is odd and the number is not prime, the vehicle will
   run on Tuesday, Thursday, Saturday and Sunday
  *  Else the vehicle will run on all the days.

- For eg:
  Vehicle No : TN75AA5115 will run on Tuesday, Thursday, Saturday and Sunday
  Vehicle No: TN75AA7116 will run on all days.
**INPUT FORMAT:**
 - Enter the Vehicle No: TN75AA5115
**OUTPUT FORMAT:**
 - TN75AA5115 will run on Tuesday, Thursday, Saturday and Sunday

In [18]:
def is_Prime(n):
    for i in range(2, int(n**0.5)):
        if n%i==0:
            return False
    return True

In [23]:
def Vehicle_allowed_on():
    s = input("Enter the Vehicle No:")
    last_digits  = s[6:]
    sum_ld  = 0
    product = 1
    
    for i in last_digits:
        sum_ld  = sum_ld + int(i)
        product = product * int(i)
    
    
    if sum_ld%2 == 0:
        if is_Prime(sum_ld):
            result = s + ' will run on Monday, Wendnesday, Friday and Sunday'
            return result
        
    elif product%2 != 0:
        if is_Prime(product):
            result = s + ' will run on Tuesday, Thursday, Saturday and Sunday'
            return result
    else:
        result = 'The Vehicle will run on all the days'
        return result
    
        

In [24]:
Vehicle_allowed_on()

Enter the Vehicle No:TN75AA7116


'The Vehicle will run on all the days'

2. It is challenge to place four queens in a 4 X 4 board such that they do not attack each
    other. Given a list of positions of four queens, write a program using functions to
    determine if the board positions are solution to the problem. If it is a solution then
    print ‘NO ATTACK’ and print ‘ATTACK’ otherwise.
**Sample Input :** 
 -  [(0,1), (1,3), (2,0), (3,2)]
 
**Output:** 
 - NO ATTACK
 
**Sample Input :**
 - [(0,1), (3,3), (2,0), (3,2)]
 
**Output:**
 - ATTACK

In [67]:
import numpy as np
def find_sol(l):
    t = [(0,0,0,0),(0,0,0,0),(0,0,0,0),(0,0,0,0)]
    board = np.matrix(t)
    for item in l:
        i = item[0]
        j = item[1]
        board[i,j] = 1
        
    res1 = 'NO ATTACK'
    res2 = 'ATTACK'
    
    #Checking if any two queens are in same row or in same column
    for item in l:
        count_row = 0
        count_col = 0
        for i in l:
            if item[0] == i[0]:
                count_row = count_row + 1
                if count_row > 1:
                    return res2
            
            elif item[1] == i[1]:
                count_col = count_col + 1
                if count_col > 1:
                    return res2
                
    #Checking the diagonals
    #diagonals1 = [(0,0),(1,1),(2,2),(3,3)]
    #diagonals2 = [(3,0),(2,1),(1,2),(0,3)]
    for item in l:
        if item[0] == item[1]:
            return res2
        elif item[0] + item[1] == 3:
            return res2
    print('The Board is\n' , board)
    return res1

In [68]:
l = [(0,1), (1,3), (2,0), (3,2)]
s = find_sol(l)
s

The Board is
 [[0 1 0 0]
 [0 0 0 1]
 [1 0 0 0]
 [0 0 1 0]]


'NO ATTACK'