<a href="https://colab.research.google.com/github/navi004/cse3041/blob/main/Pandas/temp_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
arr1 =  np.array([1,2,3])
arr1

array([1, 2, 3])

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
arr1.ndim

1

In [ ]:
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)

(3,)
3
int64


In [ ]:
f = np.arange(0,30,5)
print(f)

[ 0  5 10 15 20 25]


In [ ]:
f = np.linspace(0,5,10)
print(f)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8],[4,3,2,1]])
print(arr.shape)
arr.reshape(2,2,3)

(3, 4)


array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 4],
        [3, 2, 1]]])

In [ ]:
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
#subset = matrix[start_row:end_row, start_col:end_col]
subarray = matrix[0:2, 1:3]
subarray

array([[2, 3],
       [5, 6]])

In [ ]:
s1 = matrix[0:1,1:2]
s1

array([[2]])

In [ ]:
arr1 = np.array([1,2,3,4,5,6])
s = np.array_split(arr,3)      #split the array into 3 arrays
s

[array([1, 2]), array([3, 4]), array([5, 6])]

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
arr2 = [1,2,8,5,8,3,5]
arr2.sort()
arr2

[1, 2, 3, 5, 5, 8, 8]

In [ ]:
arr2 = np.array([1,2,8,5,8,3,5])
x = np.sort(arr2)
x

array([1, 2, 3, 5, 5, 8, 8])

In [ ]:
a1 = np.array([[1,3,5],[4,5,6]])
a2 = np.array([[2,4,6],[1,1,1],[1,2,3]])
r1 = a1.dot(a2)
r1

array([[10, 17, 24],
       [19, 33, 47]])

In [ ]:
a3 = np.array([[2,4,6],[1,2,3]])
r3 = np.vdot(a1,a3)
r3

76

In [ ]:
r1 = np.dot(a1,a2)
r1

array([[10, 17, 24],
       [19, 33, 47]])