<a href="https://colab.research.google.com/github/navi004/cse3041/blob/main/Num_pyEx_2_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#Linear Algebra in Numpy
#rank,det,trac
#eigen values,eigen vectors




In [87]:
a = np.array([[23,45,23],[20,30,40],[0,8,7]])
b = np.array([[45,60,43],[5,89,6],[12,11,10]])

r1 = a.dot(b)
r2 = np.dot(a,b)
r3 = np.vdot(a,b)
print("A\n",a,"\n")
print("B\n",b,"\n")

#print(np.linalg.matmul(a,b))

print(r1,"\n")
print(r2,"\n")
print(r3)

A
 [[23 45 23]
 [20 30 40]
 [ 0  8  7]] 

B
 [[45 60 43]
 [ 5 89  6]
 [12 11 10]] 

[[1536 5638 1489]
 [1530 4310 1440]
 [ 124  789  118]] 

[[1536 5638 1489]
 [1530 4310 1440]
 [ 124  789  118]] 

7892


In [88]:
#Sloving linear equations using numpy with linear algebra
import scipy
a = np.array([[4,3],[-5,9]])
b = np.array([20,26])
print("A\n",a)
print("B\n",b)
#x = np.linalg.inv(a).dot(b)
#or
x = np.linalg.solve(a,b)
y = scipy.linalg.solve(a,b)
print("X\n",x)
print(y)

A
 [[ 4  3]
 [-5  9]]
B
 [20 26]
X
 [2. 4.]
[2. 4.]


In [89]:
i = np.identity(3)
print("Identity matrix of order 3:\n",i)

d = np.diag([10,20,30])
print("\nDiagonal Matrix\n",d)

A = np.array([[23,45,23],[20,30,40],[0,8,7]])
r = np.linalg.matrix_rank(A)
print("\nRank of A\n",r)

t = np.trace(A)
print("\nTrace of A\n",t)

d = np.linalg.det(A)
print("\nDet of A\n",d)

p = np.linalg.matrix_power(A,2)
print("\nPower of A is raised to 1/2\n",p)



Identity matrix of order 3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Diagonal Matrix
 [[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]

Rank of A
 3

Trace of A
 60

Det of A
 -5150.000000000002

Power of A is raised to 1/2
 [[1429 2569 2490]
 [1060 2120 1940]
 [ 160  296  369]]


In [90]:
#Eigen Values
a = np.array([[1,-2j],[2j,5]])
print("Array a :\n",a)

c,d = np.linalg.eigh(a)
print("\nEigen value is :",c)
print("\nEigen vector is :",d)

Array a :
 [[ 1.+0.j -0.-2.j]
 [ 0.+2.j  5.+0.j]]

Eigen value is : [0.17157288 5.82842712]

Eigen vector is : [[-0.92387953+0.j         -0.38268343+0.j        ]
 [ 0.        +0.38268343j  0.        -0.92387953j]]


Ravel Functons


In [91]:
x = np.ravel([[1,3,5],[11,35,56]])  #Arrays get flattened in row major order(default)
y = np.ravel(x)
print(y)

z= np.ravel(x,order='F')
print(z)

[ 1  3  5 11 35 56]
[ 1  3  5 11 35 56]


Scipy - Scientific py

In [92]:
import scipy
import numpy as np
a = np.array([[7,2],[4,5]])
b = np.array([8,10])
x = scipy.linalg.solve(a,b)
print(x)

[0.74074074 1.40740741]


In [93]:
#svd - singular value decomposition is matrix decomposition method for reducing the matrix to its
x = np.array([[7,2],[4,5]])
a,b,c = scipy.linalg.svd(x)
print(a,b,c)

[[-0.76025081 -0.64962967]
 [-0.64962967  0.76025081]] [9.24504019 2.92048487] [[-0.85670524 -0.5158063 ]
 [-0.5158063   0.85670524]]


In [94]:
#Solve the following equations
import scipy
a = np.array([[4,3,2],[-2,2,3],[3,-5,2]])
b = np.array([25,-10,-4])
x = scipy.linalg.solve(a,b)
print(x)

[ 5.  3. -2.]


In [95]:
#implement a function to determine the rank,det, and inverse of a square matrix using numpy
def matCal(a):
  r = np.linalg.matrix_rank(a)
  d = np.linalg.det(a)
  i = np.linalg.inv(a)
  return r,d,i

a = np.array([[1,2,3],[4,5,6],[6,7,8]])
matCal(a)

(2,
 -4.440892098500635e-15,
 array([[ 4.50359963e+14, -1.12589991e+15,  6.75539944e+14],
        [-9.00719925e+14,  2.25179981e+15, -1.35107989e+15],
        [ 4.50359963e+14, -1.12589991e+15,  6.75539944e+14]]))